import Foundation

// Shared product copy; platform names are adapted by the native presentation layer.

public enum L10n {
    public static func allStrings(language: AppLanguage) -> [String: String] {
        Dictionary(uniqueKeysWithValues: (tables[.english] ?? [:]).keys.map { ($0, string($0, language: language)) })
    }
    public static func string(_ key: String, language: AppLanguage) -> String {
        let resolved: AppLanguage
        switch language {
        case .system:
            resolved = Locale.preferredLanguages.first?.hasPrefix("zh") == true
                ? .simplifiedChinese
                : .english
        case .english, .simplifiedChinese:
            resolved = language
        }
        return tables[resolved]?[key] ?? tables[.english]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: [
            "settings_general": "General",
            "settings_updates": "Software Update",
            "update_available": "Version %@ available",
            "update_action": "Update…",
            "update_installing": "Installing…",
            "current_version": "Version %@",
            "check_for_updates": "Check for Updates",
            "automatically_check_updates": "Check for updates automatically",
            "update_check_hint": "Checks hourly. A blue dot indicates a new version.",
            "update_check_failed": "Update check failed.",
            "usage": "Usage",
            "five_hour": "5h",
            "weekly": "7d",
            "usage_unavailable": "Usage unavailable",
            "tibo_title": "Tibo reset outlook",
            "tibo_loading": "Reading public posts…",
            "tibo_unavailable": "Public forecast unavailable",
            "tibo_24h": "Next 24h",
            "tibo_48h": "Next 48h",
            "tibo_experimental_short": "experimental",
            "tibo_forecast_heading": "Site's experimental extra-reset forecast",
            "tibo_forward_short": "28-day plan: daily improvement or full reset",
            "tibo_forward_heading": "Tibo's 28-day conditional plan",
            "tibo_forward_detail": "Each day: one clear improvement for most Codex/Work users, or a full reset. This does not promise a reset every day; no reset is counted until confirmed.",
            "tibo_posted": "Posted, Beijing time:",
            "tibo_probability_note": "These are the independent site's displayed percentages. This app does not convert the 28-day plan into a numeric probability.",
            "tibo_common_hours": "Historically common Beijing hours:",
            "tibo_historical_window": "Historical interval suggests, Beijing time:",
            "tibo_median_gap": "Median of the latest 5 post gaps:",
            "tibo_days": "days",
            "tibo_last_reset": "Last confirmed post, Beijing time:",
            "tibo_confidence": "Forecast confidence:",
            "tibo_confidence_low": "Low",
            "tibo_confidence_medium": "Medium",
            "tibo_confidence_high": "High",
            "tibo_uncertainty": "Experimental estimate from public Tibo posts, not an OpenAI schedule. A post time is not the exact time every account receives a reset. Your account's regular reset and banked reset credits are separate.",
            "tibo_updated": "Data updated, Beijing time:",
            "tibo_history": "Confirmed Tibo reset posts · Beijing time",
            "tibo_original": "Original post",
            "tibo_data": "Data:",
            "tibo_scope": "These are source summaries of confirmed extra-reset posts; open the originals for the exact text. Unrelated posts and banked reset grants are excluded. Check your own usage to confirm a reset reached your account.",
            "left": "% left",
            "resets": "Resets",
            "manage": "Manage Accounts",
            "settings": "Settings",
            "quit": "Quit",
            "switch_title": "Switch to %@?",
            "switch_body": "Codex Desktop will close and reopen. Finish or stop running Desktop tasks first. If Desktop asks to quit, complete its quit dialog. Switching stops if Desktop cannot exit normally. Existing CLI sessions stay open; new CLI sessions use the selected account.",
            "cancel": "Cancel",
            "switch": "Switch Account",
            "accounts": "Accounts",
            "back": "Back",
            "add_account": "Add Account",
            "cancel_add_account": "Cancel Adding Account",
            "remove": "Remove",
            "active": "Active",
            "remove_title": "Remove %@?",
            "remove_body": "This removes only the saved local profile from this Mac.",
            "launch_at_login": "Launch at Login",
            "launch_at_login_requires_approval": "Approval is required in System Settings.",
            "launch_at_login_unavailable": "macOS could not find this Login Item.",
            "open_system_settings": "Open System Settings",
            "show_menu_bar_percentage": "Show Percentage in Menu Bar",
            "status_bar_usage_window": "Status Bar Usage",
            "show_five_hour_usage": "Show 5-hour Usage",
            "language": "Language",
            "system_default": "System Default",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "A browser window will open for Codex sign-in.",
            "sign_in_pending_hint": "Complete sign-in in the browser, or cancel here if you closed it.",
            "no_accounts": "No saved accounts",
            "ok": "OK",
            "operation_failed": "Operation failed",
            "switch_failed": "Account switch failed",
            "register_current_account": "Register Current Account",
            "active_unconfirmed": "Active account could not be confirmed",
            "switched_reopen_title": "Account switched",
            "switched_reopen_message": "The selected account is active, but Codex Desktop could not be reopened. Open Codex manually to continue.",
        ],
        .simplifiedChinese: [
            "settings_general": "通用",
            "settings_updates": "软件更新",
            "update_available": "发现新版本 %@",
            "update_action": "更新…",
            "update_installing": "正在安装…",
            "current_version": "当前版本 %@",
            "check_for_updates": "检查更新",
            "automatically_check_updates": "自动检查更新",
            "update_check_hint": "每小时检查一次，有新版本时显示蓝点。",
            "update_check_failed": "检查更新失败。",
            "usage": "用量",
            "five_hour": "5 小时",
            "weekly": "7 天",
            "usage_unavailable": "用量暂不可用",
            "tibo_title": "Tibo 额外重置预测",
            "tibo_loading": "正在读取公开推文…",
            "tibo_unavailable": "公开预测暂不可用",
            "tibo_24h": "未来 24 小时",
            "tibo_48h": "未来 48 小时",
            "tibo_experimental_short": "实验性",
            "tibo_forecast_heading": "独立站点展示的额外重置预测（实验性）",
            "tibo_forward_short": "28 天计划：每日改进或完整重置",
            "tibo_forward_heading": "Tibo 的 28 天条件性计划",
            "tibo_forward_detail": "未来 28 天，每天推出一项对大多数 Codex/Work 用户有明显帮助的改进，或进行一次完整重置。这不等于每天都会重置；未确认的重置不计入历史。",
            "tibo_posted": "发布时间（北京时间）：",
            "tibo_probability_note": "百分比原样取自独立站点的展示值；本应用没有把这条 28 天计划换算成数字概率。",
            "tibo_common_hours": "历史常见北京时间：",
            "tibo_historical_window": "按历史间隔推算的参考窗口（北京时间）：",
            "tibo_median_gap": "最近 5 段发帖间隔的中位数：",
            "tibo_days": "天",
            "tibo_last_reset": "最近确认推文（北京时间）：",
            "tibo_confidence": "预测置信度：",
            "tibo_confidence_low": "低",
            "tibo_confidence_medium": "中",
            "tibo_confidence_high": "高",
            "tibo_uncertainty": "这是根据 Tibo 公开推文得到的实验性估计，并非 OpenAI 时间表。发帖时间也不等于每个账号实际到账时间。账号自身的正常重置与可用重置次数是另外两件事。",
            "tibo_updated": "数据更新（北京时间）：",
            "tibo_history": "已确认的 Tibo 重置推文 · 北京时间",
            "tibo_original": "原帖",
            "tibo_data": "数据：",
            "tibo_scope": "下方文字是数据源摘要，准确原文请打开原帖。仅列出已确认的额外重置推文；无关推文和赠送重置次数不计入。是否到账请以本人账号用量为准。",
            "left": "% 剩余",
            "resets": "重置于",
            "manage": "管理账号",
            "settings": "设置",
            "quit": "退出应用",
            "switch_title": "切换到 %@？",
            "switch_body": "Codex Desktop 将关闭并重新打开。请先完成或停止正在运行的 Desktop 任务。如果 Desktop 显示退出提示，请处理该提示；无法正常退出时会停止切换。现有 CLI 会话保持运行，新 CLI 会话将使用所选账号。",
            "cancel": "取消",
            "switch": "切换账号",
            "accounts": "账号",
            "back": "返回",
            "add_account": "添加账号",
            "cancel_add_account": "取消添加账号",
            "remove": "移除",
            "active": "当前",
            "remove_title": "移除 %@？",
            "remove_body": "此操作只会移除这台 Mac 上保存的本地账号档案。",
            "launch_at_login": "登录时自动启动",
            "launch_at_login_requires_approval": "需要在系统设置中允许此登录项。",
            "launch_at_login_unavailable": "macOS 找不到此登录项。",
            "open_system_settings": "打开系统设置",
            "show_menu_bar_percentage": "在菜单栏显示百分比",
            "status_bar_usage_window": "状态栏显示额度",
            "show_five_hour_usage": "显示 5 小时用量",
            "language": "语言",
            "system_default": "跟随系统",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "将打开浏览器进行 Codex 登录。",
            "sign_in_pending_hint": "请在浏览器完成登录；如果已关闭页面，可在此取消。",
            "no_accounts": "暂无已保存账号",
            "ok": "好",
            "operation_failed": "操作失败",
            "switch_failed": "账号切换失败",
            "register_current_account": "登记当前登录账号",
            "active_unconfirmed": "无法确认当前账号",
            "switched_reopen_title": "账号已切换",
            "switched_reopen_message": "所选账号已经生效，但 Codex Desktop 未能重新打开。请手动打开 Codex 继续使用。",
        ],
    ]
}
